#!/usr/bin/env bash

version=`node -v`
node-waf configure build
if [ -e build/default/createpair.node ]; then
  cp build/default/createpair.node "lib/createpair.$version.node"
elif [ -e build/default/createpair.node ]; then
  cp build/default/createpair.node "lib/createpair.$version.node"
fi
